### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/reasyeda#16]
Specific expectations for this milestone: Mechanics

Comments
For your Python GitHub repo, Rogue branch "sukhleen999-patch-1". Please remember to update your branches by merging them and deleting them if they are not your function. Your R GitHub repo looks excellent! Your R readme, please put author names on that!

Lastly, James did not commit enough to the R repo.

**Comment by Luming-ubc** [comment]
Hi Andy,

Thanks for the detailed feedback. We just removed the redundant branches, and we will make sure to delete unnecessary ones before submission in this milestone. Also, we just added the authors in our readme file for this R package.

I believe the James @jamesktkim was mainly focusing on the submissions and managing project issues for Milestone 2. But, for sure he will have enough uploads and commit for this milestone. 

Thanks!
